### ISSUE TITLE
Supermin and Docker-Toolbox

### ISSUE THREAD

**Issue by Govinda-Fichtner** [libguestfs/supermin#14]
I am trying to build images with guestfish in a Docker container. 
I am using the [Docker-Toolbox](https://www.docker.com/docker-toolbox) with [Boot2Docker](https://github.com/boot2docker/boot2docker) on Mac.

When I try to create a new image with guestfish in a running Docker container I get the following error:
```
root@7bc0bf6f6c4f:/test# guestfish -N bootroot:ext2:ext4:1G:64M
libguestfs: error: /usr/bin/supermin exited with error status 1.
To see full error messages you may need to enable debugging.
See http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
```

Any idea why this happens?

**Comment by rwmjones** [comment]
We don't use the proprietary github issue tracker.  I'll answer this on the libguestfs mailing list shortly.
