### ISSUE TITLE
init: Use pivot_root, not chroot

### ISSUE THREAD

**Issue by cgwalters** [libguestfs/supermin#19]
See https://github.com/containers/bootc/pull/203

TL;DR using `chroot` instead of `pivot_root` breaks things that want to enter the root mountns from a different mount namespace.

**Comment by rwmjones** [comment]
`pivot_root` can't be used, see: https://github.com/libguestfs/supermin/blob/c8e79b7d62730f850f9e5d46c3747f414198b902/init/init.c#L282 and https://www.kernel.org/doc/html/v5.10/filesystems/ramfs-rootfs-initramfs.html (search for `pivot_root`).  I don't know if this has changed, but Linux docs suggest not.

**Comment by cgwalters** [comment]
Thanks, sorry for not reading the comment above.  I'm fine to close this as WONTFIX. 

BTW, I think now that Linux supports root-on-virtiofs we could basically obsolete the supermin disk image building and this code I believe?

**Comment by rwmjones** [comment]
virtiofs is quite a bit more heavyweight than some files zipped up into a cpio.  It involves running a daemon at least.

BTW what actually goes wrong because we don't use `pivot_root`?  I don't think I've encountered any problem with it before.

**Comment by cgwalters** [comment]
- `chroot` changes just the process view of the filesystem
- `pivot_root` changes the mount namespace itself

The difference becomes visible when a process in a different mount namespace wants to enter the original mountns.

**Comment by dustymabe** [comment]
Note also the use of `chroot` means that user namespaces can't be used:

```
bash-5.2# unshare -U
unshare: unshare failed: Operation not permitted
```

This is by design (thanks @giuseppe for the link): https://github.com/torvalds/linux/blob/41bccc98fb7931d63d03f326a746ac4d429c1dd3/kernel/user_namespace.c#L98-L107
