### ISSUE TITLE
Fails compilation with -fPIE

### ISSUE THREAD

**Issue by Calderweis** [libguestfs/supermin#21]
This is the output I get from running make. When adding -fPIE to the CFLAGS I still get the same error ;
`/usr/bin/ld: supermin-ext2fs-c.o: relocation R_X86_64_32 against .rodata.str1.1 can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: supermin-format-ext2-init-c.o: relocation R_X86_64_32 against .rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: supermin-fnmatch-c.o: relocation R_X86_64_32S against .rodata can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: supermin-glob-c.o: relocation R_X86_64_32S against .rodata can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: supermin-librpm-c.o: relocation R_X86_64_32 against .rodata.str1.1 can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: supermin-realpath-c.o: relocation R_X86_64_32 against .rodata.str1.1 can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status`

**Comment by rwmjones** [comment]
Probably the OCaml compiler is using PIC by default.  Try doing:
```
make clean
./configure CFLAGS="-fPIC -O2 -g"
make
```

**Comment by Calderweis** [comment]
That solved it!
